version: "3.7"
services:
  api:
    container_name: medical-procedures-server
    build: "./medical-procedures-server"
    restart: always
    ports:
      - 3000:3000
    environment:
      SECRET: mysecretkey
      TOKEN_EXP: 3600000
      TOKEN_EXP_REFRESH: 120
      TIMEZONE: America/Sao_Paulo
      DB_HOST: #APP_HOST
      DB_DATABASE: #APP_DATABASE
      DB_USER: #APP_USER
      DB_PASS: #APP_PASS
  client:
    container_name: medical-procedures-client
    build: "./medical-procedures-client"
    ports:
      - 8080:80
    environment:
      API_URL: http://localhost:3000