version: "3.8"
services:
  medicalapi:
    container_name: medical-procedures-server
    build: "./medical-procedures-server"
    restart: always
    ports:
      - 3000:3000
    environment:
      SECRET: mysecretkey
      TOKEN_EXP: 3600000
      TOKEN_EXP_REFRESH: 120
      TIMEZONE: America/Sao_Paulo
      DB_HOST: medicaldb
      DB_DATABASE: medical
      DB_USER: root
      DB_PASS: example
    depends_on:
      - "medicaldb"
  medicaldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  medicaladminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  medicalclient:
    container_name: medical-procedures-client
    build: "./medical-procedures-client"
    ports:
      - 8080:80
    environment:
      API_URL: http://localhost:3000
